version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: jpa-training-db
    environment:
      POSTGRES_DB: jpatraining
      POSTGRES_USER: training
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: