spring:
  application:
    name: jpadojo
  
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatraining
    username: training
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.boot.sql.init: DEBUG
    root: INFO